name: CI para AvisosApp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validar sintaxis del servidor
        run: |
          python -m py_compile Avisos_y_notas_servidor.py

      - name: Ejecutar servidor en segundo plano
        run: |
          uvicorn Avisos_y_notas_servidor:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: Crear un aviso de prueba
        run: |
          curl -X POST http://127.0.0.1:8000/avisos \
            -H "Content-Type: application/json" \
            -d '{"titulo": "Aviso de CI", "contenido": "Este aviso fue creado automáticamente"}'

      - name: Verificar que el aviso fue creado
        run: |
          curl -X GET http://127.0.0.1:8000/avisos | grep "Aviso de CI"
