name: CI para AvisosApp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validar sintaxis del servidor
        run: |
          python -m py_compile Avisos_y_notas_servidor.py

      - name: Ejecutar servidor y probar endpoint
        run: |
          uvicorn Avisos_y_notas_servidor:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl -X GET http://127.0.0.1:8000/avisos
